services:
  sonarqube:
    image: sonarqube:10-community
    ports:
      - '9000:9000'
    volumes:
      - ./sonar_data:/opt/sonarqube/data
      - ./sonar_extensions:/opt/sonarqube/extensions
      - ./sonar_logs:/opt/sonarqube/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://sonarqube:9000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 10

  api:
    build:
      context: api/
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    command: poetry run smm-rest --host 0.0.0.0 --port 8000

  webapp:
    build:
      context: webapp/
      dockerfile: Dockerfile.dev
    platform: linux/amd64
    ports:
      - '3000:3000'
    volumes:
      - ./webapp:/app
    command: npm run dev -- -H 0.0.0.0